## Data Preparation
First we need to prepare the data so that we can input it into the model.

In [31]:
# load the necessary libraries
import pandas as pd

# Disable the warning on chained assignments
pd.options.mode.chained_assignment = None 
import numpy as np

In [2]:
# Open the spreadsheet that you downloaded from Google Sheets
sheet = pd.read_excel("data/Implicit hate speech.xlsx")

# View the first 5 instances of the sheet
sheet.head()

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"As part of #myrefugeestory, Mohamed Madi and B...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.facebook.com/228735667216_10153273...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,###,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN

In [70]:
# Let's look at the statistics of the sheet
sheet.describe(include="all")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
count,5868,5782,5791,5791,571.000000,329.000000,329.000000,329.000000,241.000000
unique,5838,5722,27,31,NaN,NaN,NaN,NaN,NaN
top,###,-*-*-*- Mary mother of Jesus is depicted weari...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
freq,31,11,2873,3015,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.576182,0.316109,0.106383,0.303951,0.331950
std,NaN,NaN,NaN,NaN,0.494595,0.465664,0.308797,0.460663,0.471893
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

In [71]:
# In our experiments, we are interested only in comments, not posts (posts are not annotated), so let's remove all instances that don't have anything (have NaN values) in the Type column
sheet = sheet.dropna(subset=["Type"])

# Let's see the results
sheet.describe(include="all")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
count,5791,5782,5791,5791,571.000000,329.000000,329.000000,329.000000,241.000000
unique,5791,5722,27,31,NaN,NaN,NaN,NaN,NaN
top,https://www.facebook.com/228735667216_10153273...,-*-*-*- Mary mother of Jesus is depicted weari...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
freq,1,11,2873,3015,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.576182,0.316109,0.106383,0.303951,0.331950
std,NaN,NaN,NaN,NaN,0.494595,0.465664,0.308797,0.460663,0.471893
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

In [72]:
# Let's look at the new sheet (first 3 instances)
sheet.head(3)

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5,https://www.facebook.com/228735667216_10153273...,-*-*-*- Why should we? It's the biggest humani...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
6,https://www.facebook.com/228735667216_10153273...,-*-*-*- these refugees adult males are cowards...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN

In [73]:
# Following Nikola's instruction, we'll also delete the "-*-*-*- " part from the comments.
# We need to add "\" before the "*" because otherwise it is understood as a special regex character.

sheet["Comment"] = sheet["Comment"].str.replace("-\*-\*-\*- ", "")
sheet["Comment"] = sheet["Comment"].str.replace("-\*-\*-\*-", "")

# Let's look at the sheet
sheet.head(5)

C:\Users\TajaK\AppData\Local\Temp\ipykernel_13000\1628127234.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  sheet["Comment"] = sheet["Comment"].str.replace("-\*-\*-\*- ", "")
C:\Users\TajaK\AppData\Local\Temp\ipykernel_13000\1628127234.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  sheet["Comment"] = sheet["Comment"].str.replace("-\*-\*-\*-", "")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5,https://www.facebook.com/228735667216_10153273...,Why should we? It's the biggest humanitarian c...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
6,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN
7,https://www.facebook.com/228735667216_10153273...,Does Syria own the BBC?.........,Acceptable speech|Other offensive,No target|Journalist or medium,NaN,NaN,NaN,NaN,NaN
8,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN

In [74]:
# Let's delete the empty comments because they do not carry any information.
# After this, the count of ### and Comment will be the same.
sheet = sheet.dropna(subset=["Comment"])

sheet.describe(include="all")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
count,5782,5782,5782,5782,571.000000,329.000000,329.000000,329.000000,241.000000
unique,5782,5707,27,31,NaN,NaN,NaN,NaN,NaN
top,https://www.facebook.com/228735667216_10153273...,Mary mother of Jesus is depicted wearing it in...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
freq,1,11,2864,3006,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.576182,0.316109,0.106383,0.303951,0.331950
std,NaN,NaN,NaN,NaN,0.494595,0.465664,0.308797,0.460663,0.471893
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

In [75]:
# There are also some empty comments that have an empty string
discarded_sheet = sheet[sheet["Comment"].str.split().str.len() < 1]
discarded_sheet

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
90,https://www.facebook.com/228735667216_10153273...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
961,https://www.facebook.com/164305410295882_27747...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
3556,https://www.facebook.com/164305410295882_27690...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
3584,https://www.facebook.com/164305410295882_27690...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
3980,https://www.facebook.com/164305410295882_11105...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
4604,https://www.facebook.com/164305410295882_24273...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5109,https://www.facebook.com/10513336322_101537662...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5110,https://www.facebook.com/10513336322_101537662...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5111,https://www.facebook.com/10513336322_101537662...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5112,https://www.facebook.com/10513336322_101537662...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5725,https://www.facebook.com/10513336322_101537662...,,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN

In [76]:
# Lets delete the comments that have text length less than 1 - that are empty
sheet = sheet[sheet["Comment"].str.split().str.len() >= 1]

sheet.describe(include="all")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
count,5771,5771,5771,5771,571.000000,329.000000,329.000000,329.000000,241.000000
unique,5771,5706,27,31,NaN,NaN,NaN,NaN,NaN
top,https://www.facebook.com/228735667216_10153273...,Mary mother of Jesus is depicted wearing it in...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
freq,1,11,2853,2995,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.576182,0.316109,0.106383,0.303951,0.331950
std,NaN,NaN,NaN,NaN,0.494595,0.465664,0.308797,0.460663,0.471893
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

In [77]:
# Let's analyze whether any of the comments are duplicated
sheet[sheet.Comment.duplicated(keep=False)].sort_values("Comment")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
5584,https://www.facebook.com/10513336322_101537662...,.. One Month of Islam and Multiculturalism in ...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
5397,https://www.facebook.com/10513336322_101537662...,.. One Month of Islam and Multiculturalism in ...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
1886,https://www.facebook.com/10513336322_101528254...,A difficult concept for most people to underst...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
1821,https://www.facebook.com/10513336322_101528254...,A difficult concept for most people to underst...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
630,https://www.facebook.com/228735667216_10153107...,All of u forgot ab Israel. When they first arr...,Background offensive,Migrants,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
351,https://www.facebook.com/228735667216_10153107...,https://youtu.be/UkIocH91j0w,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
3244,https://www.facebook.com/228735667216_10153107...,https://youtu.be/UkIocH91j0w,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
384,https://www.facebook.com/228735667216_10153107...,https://youtu.be/UkIocH91j0w,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
4112,https://www.facebook.com/164305410295882_11105...,women are to cover in christianity when in pra...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
3955,https://www.facebook.com/164305410295882_11105...,women are to cover in christianity when in pra...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN

In [78]:
# We have 104 duplicated texts - we need to remove the duplicates
sheet = sheet.drop_duplicates("Comment")
sheet.describe(include="all")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution
count,5706,5706,5706,5706,571.000000,329.000000,329.000000,329.000000,241.000000
unique,5706,5706,27,31,NaN,NaN,NaN,NaN,NaN
top,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN
freq,1,1,2821,2965,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.576182,0.316109,0.106383,0.303951,0.331950
std,NaN,NaN,NaN,NaN,0.494595,0.465664,0.308797,0.460663,0.471893
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

In [79]:
# Let's analyze the statistics of the Implicit which interests us in Experiment 1
print(sheet.Implicit.value_counts())
print(sheet.Implicit.value_counts(normalize = True))

1.0    329
0.0    242
Name: Implicit, dtype: int64
1.0    0.576182
0.0    0.423818
Name: Implicit, dtype: float64

In [80]:
# Let's analyze the statistics of the Type which will interest us in Experiment 2
# See which classes we have:
print(sheet.Type.unique())
# See the statistics:
print(sheet.Type.value_counts())

['Acceptable speech' 'Background offensive'
 'Acceptable speech|Other offensive' 'Other offensive'
 'Acceptable speech|Background offensive'
 "Acceptable speech|Other offensive|Don't know"
 'Other offensive|Background offensive' 'Background violence'
 'Background violence|Background offensive'
 'Other offensive|Acceptable speech'
 "Other offensive|Acceptable speech|Background violence|Don't know"
 "Acceptable speech|Other offensive|Don't know|Background offensive"
 'Inappropriate' 'Acceptable speech|Inappropriate' 'Other threat'
 'Other threat|Other offensive'
 'Acceptable speech|Other offensive|Background offensive'
 'Background offensive|Inappropriate' 'Other offensive|Inappropriate'
 'Other offensive|Background violence' "Acceptable speech|Don't know"
 'Acceptable speech|Other offensive|Inappropriate'
 'Other threat|Background violence' 'Other threat|Acceptable speech'
 'Other threat|Other offensive|Background offensive'
 'Other threat|Acceptable speech|Other offensive'
 'Acceptable speech|Background offensive|Inappropriate']
Acceptable speech                                                    2821
Background offensive                                                 1286
Other offensive                                                      1174
Acceptable speech|Other offensive                                     149
Acceptable speech|Background offensive                                 94
Background violence                                                    53
Other offensive|Background offensive                                   44
Inappropriate                                                          23
Other threat                                                           21
Other offensive|Inappropriate                                           6
Background violence|Background offensive                                6
Acceptable speech|Other offensive|Background offensive                  6
Acceptable speech|Inappropriate                                         5
Other threat|Other offensive                                            2
Acceptable speech|Other offensive|Don't know                            2
Acceptable speech|Other offensive|Inappropriate                         2
Other threat|Acceptable speech|Other offensive                          2
Acceptable speech|Other offensive|Don't know|Background offensive       1
Other offensive|Acceptable speech|Background violence|Don't know        1
Other offensive|Acceptable speech                                       1
Background offensive|Inappropriate                                      1
Other offensive|Background violence                                     1
Acceptable speech|Don't know                                            1
Other threat|Background violence                                        1
Other threat|Acceptable speech                                          1
Other threat|Other offensive|Background offensive                       1
Acceptable speech|Background offensive|Inappropriate                    1
Name: Type, dtype: int64

In [81]:
# As the Experiment 2 will be a binary task: Acceptable vs Hate Speech, we need to create a column with only these two classes.
# First, let's copy the values in a new column
sheet["binary-hate-speech"] = sheet["Type"]

sheet.head(1)

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech

In [82]:
# As Experiment 2 will be based on binary values: acceptable speech and hate speech, let's transform the labels from the Type accordingly.

# mark with "discard" all instances which are annotated with both categories at the same time (contains "|Acceptable speech" or "Acceptable speech|" - or is marked by "|" and you need to add "\" before the symbol "|" in the string "|Acceptable speech" to find it)
sheet['binary-hate-speech'] = np.where(sheet['binary-hate-speech'].str.contains("\|Acceptable speech|Acceptable speech\|", regex = True, na = False),'discard',sheet['binary-hate-speech'])

# See the remaining labels
sheet["binary-hate-speech"].unique()

array(['Acceptable speech', 'Background offensive', 'discard',
       'Other offensive', 'Other offensive|Background offensive',
       'Background violence', 'Background violence|Background offensive',
       'Inappropriate', 'Other threat', 'Other threat|Other offensive',
       'Background offensive|Inappropriate',
       'Other offensive|Inappropriate',
       'Other offensive|Background violence',
       'Other threat|Background violence',
       'Other threat|Other offensive|Background offensive'], dtype=object)

In [83]:
# mark as "Hate speech" all instances that are not "Acceptable speech" or "discard"
sheet['binary-hate-speech'] = np.where(((sheet['binary-hate-speech'] != "Acceptable speech") & (sheet['binary-hate-speech'] != "discard")),'Hate speech',sheet['binary-hate-speech'])

sheet.head()

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
5,https://www.facebook.com/228735667216_10153273...,Why should we? It's the biggest humanitarian c...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
6,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech
7,https://www.facebook.com/228735667216_10153273...,Does Syria own the BBC?.........,Acceptable speech|Other offensive,No target|Journalist or medium,NaN,NaN,NaN,NaN,NaN,discard
8,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech

In [84]:
# Analyze the statistics of the results
sheet["binary-hate-speech"].value_counts()

Acceptable speech    2821
Hate speech          2619
discard               266
Name: binary-hate-speech, dtype: int64

In [85]:
sheet["binary-hate-speech"].value_counts()

Acceptable speech    2821
Hate speech          2619
discard               266
Name: binary-hate-speech, dtype: int64

In [86]:
# Before we create additional dataframes for specific experiments and save this one, restart the index.
sheet.reset_index(inplace=True)
sheet.head()

,index,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
0,4,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
1,5,https://www.facebook.com/228735667216_10153273...,Why should we? It's the biggest humanitarian c...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
2,6,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech
3,7,https://www.facebook.com/228735667216_10153273...,Does Syria own the BBC?.........,Acceptable speech|Other offensive,No target|Journalist or medium,NaN,NaN,NaN,NaN,NaN,discard
4,8,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech

In [87]:
# Delete the additional column that was created
sheet = sheet.drop(columns="index")
sheet.head(1)

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
0,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech

In [88]:
# Save the analyzed dataframe for further use
sheet.to_csv("data/hate-speech-prepared-spreadsheet.csv", sep="\t")

In [35]:
# You can reopen the dataframe in such way:
main_df = pd.read_csv("data/hate-speech-prepared-spreadsheet.csv", sep= "\t", index_col = 0)

main_df.head()

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
0,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
1,https://www.facebook.com/228735667216_10153273...,Why should we? It's the biggest humanitarian c...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech
2,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech
3,https://www.facebook.com/228735667216_10153273...,Does Syria own the BBC?.........,Acceptable speech|Other offensive,No target|Journalist or medium,NaN,NaN,NaN,NaN,NaN,discard
4,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech

In [33]:
# Let's analyze the average text length (this will be useful to know what should the max token length be when setting the Transformer parameters)
# Add a column with this information - we calculate the length by first splitting the string in column "Comment" to a list of words (split()) and then calculating the number of elements in the list (len())
main_df['text_length'] = main_df["Comment"].str.split().str.len()

# See the statistics
main_df.text_length.describe()

count    5706.000000
mean       34.013495
std        55.640073
min         1.000000
25%         8.000000
50%        18.000000
75%        38.000000
max      1387.000000
Name: text_length, dtype: float64

In [35]:
print(main_df.text_length.describe().to_markdown())

|       |   text_length |
|:------|--------------:|
| count |     5706      |
| mean  |       34.0135 |
| std   |       55.6401 |
| min   |        1      |
| 25%   |        8      |
| 50%   |       18      |
| 75%   |       38      |
| max   |     1387      |

In [36]:
# Lets analyze texts that are longer than 1000 words
main_df[main_df.text_length > 1000]

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech,text_length
66,https://www.facebook.com/228735667216_10153273...,Delfina Jones 1. I don't worship a pedophile. ...,Other offensive,No target|Commenter,1.0,0.0,0.0,1.0,0.0,Hate speech,1387

In [37]:
# Let's check if the text is okay
main_df.iloc[66].Comment

'Delfina Jones 1. I don\'t worship a pedophile. I respect and adore a prophet. Placing him into the category of a pedophile is beyond pathetic as he lived 1400 YEARS. 1400 years. People change in 1400 years. In the future, people would call us pedophiles for marrying people at the age of 20-28. That\'s the problem that you don\'t seem to understand. It was a norm to marry women at a young age. How can I call someone who lived more than a thousand years ago a rapist if it was a normal thing for EVERY human on the planet at that point to marry young females? Marriage is also a choice in islam. I\'m a young woman yet my parents don\'t force me to marry at a young age. THAT is culture. A culture that has ruined the true image of islam by mixing its own blend to make islam look "nice" for them. But it isn\'t. 2. Slavery is allowed but we rather call it housekeeping as slavery basically means a slave being owned to a master and does everything that the master tells him to do. Islam is against that as it says that all "slaves" should wear the same clothes as the master, eat at the dinnertable with its master and to not be forced to do work that is beyond their strength...kind of sounds like a familymember to me. You\'re not allowed to rape anyone because that is considered Zina: an act that is forbidden by Allah. And the whole marriage by 4 women but women can only marry 1 man: I don\'t remember exactly but it was something to do with there being more women than men in our world (because war). However, that doesn\'t mean that a man can just randomly go get a second wife just like that. He has to ask his first wife and if she agrees (nowadays a i doubt that), he has to go through his finances so he knows that he\'s able to take care of a second. I doubt even more that there will be a woman that would want to share their love for a husband with another which makes it harder for a man to find a second wife. If men aren\'t capable of taking care of one wife (as it says in the quran but you don\'t seem to care about that), the man MUST settle with having one. Also, nowehere in the quran does it state how many husbands a woman can have but yes it does say a man can have 4 wives. For women, it would mean that she could marry as many as she pleases (though WHY would a woman wanna do that? I don\'t wanna have more than one husband and I know for certain that we would enjoy putting our efforts and love for one guy and not many and men would not enjoy having to share their love for one woman but some regions in the world have different norms (which i\'m TRYING TO POINT OUT because the prophet and those who lived with him existed in a different time with DIFFERENT norms). Today we have somewhat the same norms but because of differences in timeline, we change alot for the better but know that we can follow the same norms. It\'s just that it\'s very important to make everyone and God happy . 2. Slavery is allowed but we rather call it housekeeping as slavery basically means a slave being owned to a master and does everything that the master tells him to do. Islam is against that as it says that all "slaves" should wear the same clothes as the master, eat at the dinnertable with its master and to not be forced to do work that is beyond their strength...kind of sounds like a familymember to me. You\'re not allowed to rape anyone because that is considered Zina: an act that is forbidden by Allah. And the whole marriage by 4 women but women can only marry 1 man: I don\'t remember exactly but it was something to do with there being more women than men in our world (because war). However, that doesn\'t mean that a man can just randomly go get a second wife just like that. He has to ask his first wife and if she agrees (nowadays a i doubt that), he has to go through his finances so he knows that he\'s able to take care of a second. I doubt even more that there will be a woman that would want to share their love for a husband with another which makes it harder for a man to find a second wife. If men aren\'t capable of taking care of one wife (as it says in the quran but you don\'t seem to care about that), the man MUST settle with having one. 3. You want to know the positives that Islam has brought 30 YEARS FROM NOW? You weren\'t being clear with your point as you challenged me to state the positive things that Islam has brought to the west. I did but you are so reluctant to holding on to your opinion because 30 years ago, many ARABIC countries, not islamic, ARABIC countries decided to rebel against their leaders, resulting in new leaders and more rebellious groups are formed to overthrow the leaders. They use anything that is necessary to take down the leader and when they do, they have NO IDEA on how to govern at all. Are these muslims? Of course not. If strongly hold on to your actions and blame people when clearly there were better options (peace deals), then you\'re not a muslim. You\'re an idiot. Ignorant idiots. 4. The BIGGEST issue that I have with people criticizing isla m is that they point out issues with countries and how they govern. Both sides (the west AND "muslim" countries) are doing everything they can, knowingly and unknowingly sabbotaging the religion that once stated that through knowledge and peace, there will be victory. The problem isn\'t interely muslim countries, it\'s nationalism. It still exists and is the main reason why many have such hatred and rage towards others. even countries considered "muslim" have a grudge against each other (look at Saudi Arabia and Iran). Islam is a religion that unifies people, wether colour, race, sex, age or ethnicity. All it takes is an open mind and you might learn things beyond the screams and echoes from the media. I have watched Christianity and its history, I have seen the issues with Zionism vs Judaism, I have heard of people who believe in Buddhism but do terrible acts against others. WE humans are responsible for OUR actions and what we bring forth to our religion. Islam is always waiting for people to listen to it but many have always glared behind for other things and sometimes turned their cheeks. I CAN BRING a good image of Islam and I can also BRING a bad image of it aswell but Islam as a whole is never changed. It stays the same. Only I can become distorted or bad. THAT is why you see muslims bombing themselves and killing in the name of God: They are enraged, confused and don\'t know about Islam. When you live in a place where foreigners (US) have bombed, destroyed unity, taken their properties and placed terrible leaders there, what are the odds that you end up becoming confused of the situation, just like many, and do everything necessary to take back the good times. Suddenly you get it back but what CAN you do? You don\'t know how to govern, you know how to fight. All rebellious groups start out well, fighting for justice and then suddenly along the way, they become confused and even mad with power and strength that God has given them, only to use it to hurt others and blame God for that. There is a problem in these places but to solve it, PEOPLE NEED TO STOP BALING EVERYTHING ON ISLAM AND GET THEIR BUTTS OFF OF THESE PLACES and I\'m talking mainly about the US. PS: My religion is MY choice but just like you have your choice, I wish to respect it and the same should go with you.'

We see that 75% of comments have 38 or less words, so we can use a smaller maximum token size as a parameter in Transformers.

### Datasets for the experiments

Let's create the datasets for the two experiments. Simple Transformers require the data to be in the following format:

"The train data should be contained in a Pandas Dataframe with at least two columns. One column should contain the text and the other should contain the labels. The text column should be of datatype str, while the labels column should be of datatype int (0 or 1).

If the dataframe has a header row, the text column should have the heading text and the labels column should have the heading labels."

#### Dataset for Experiment 1
In experiment 1, we have two classes: implicit (1) or explicit (0).

In [91]:
# Create a new dataframe from the original sheet, discarding all instances that are not annotated for implicitness.
sheet1 = sheet.dropna(subset=["Implicit"])

# See the sheet1 size - number of rows and columns:
sheet1.shape

(571, 10)

In [92]:
# View the sheet1
sheet1.head()

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
2,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech
4,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech
5,https://www.facebook.com/228735667216_10153273...,You only see what you want to see. Pretty much...,Other offensive,Commenter,1.0,1.0,1.0,0.0,0.0,Hate speech
7,https://www.facebook.com/228735667216_10153273...,Delfina Jones are you one of the Donald Trump'...,Other offensive,Commenter,1.0,1.0,1.0,1.0,0.0,Hate speech
8,https://www.facebook.com/228735667216_10153273...,Europeans who immigrated during WW2 weren't br...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,Hate speech

In [93]:
# Because the categories need to be encoded as integers not floats, we change that:
sheet1["Implicit"] = sheet1["Implicit"].astype("int")

# View the sheet
sheet1.head(1)

C:\Users\TajaK\AppData\Local\Temp\ipykernel_13000\684844395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sheet1["Implicit"] = sheet1["Implicit"].astype("int")

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
2,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0,NaN,NaN,NaN,NaN,Hate speech

In [94]:
# Now we prepare the dataframe as instructed by the SimpleTransformers, taking only the two relevant columns - Comment and Implicit
impl_sheet = sheet1[["Comment", "Implicit"]]

# Rename the columns
impl_sheet.columns=["text", "labels"]

impl_sheet

                                                   text  labels
2     these refugees adult males are cowards for not...       0
4     They are all mentally jerking off to the refug...       0
5     You only see what you want to see. Pretty much...       1
7     Delfina Jones are you one of the Donald Trump'...       1
8     Europeans who immigrated during WW2 weren't br...       0
...                                                 ...     ...
1089  I'd like military-aged Syrian men to pick up a...       1
1090  It won't happen as oil and water do not -Will ...       1
1094  You basically killed him yourself trying for a...       0
1095  Does he not realize that ISIS terrorists are a...       0
1096  My message to Syrians, take care of ur kids un...       0

[571 rows x 2 columns]

In [95]:
# Save the created file in a csv format
impl_sheet.to_csv("data/implicitness_binary_dataset.csv", sep="\t")

#### Dataset for experiment 2
In this experiment, we are interested in two classes: acceptable speech (0) and hate speech (1).

In [36]:
sheet = main_df

sheet.head(1)

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
0,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,Acceptable speech

In [37]:
# Create a new dataframe from the original sheet, discarding all instances that have "discard" in column.
sheet2 = sheet[sheet["binary-hate-speech"] != "discard"]

sheet2.shape

(5440, 10)

In [38]:
# See the statistics
sheet2["binary-hate-speech"].value_counts()

Acceptable speech    2821
Hate speech          2619
Name: binary-hate-speech, dtype: int64

In [39]:
# Change the labels in binary-hate-speech into 0 and 1
sheet2['binary-hate-speech'] = np.where((sheet2['binary-hate-speech'] == "Acceptable speech"),'0',sheet2['binary-hate-speech'])
sheet2['binary-hate-speech'] = np.where((sheet2['binary-hate-speech'] == "Hate speech"),'1',sheet2['binary-hate-speech'])

In [40]:
sheet2.head()

,###,Comment,Type,Target,Implicit,Metaphor/metonymy,Sarcasm/humor,Rhetorical question,Circumlocution,binary-hate-speech
0,https://www.facebook.com/228735667216_10153273...,Can we shut up about refugees already?,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,0
1,https://www.facebook.com/228735667216_10153273...,Why should we? It's the biggest humanitarian c...,Acceptable speech,No target,NaN,NaN,NaN,NaN,NaN,0
2,https://www.facebook.com/228735667216_10153273...,these refugees adult males are cowards for not...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,1
4,https://www.facebook.com/228735667216_10153273...,They are all mentally jerking off to the refug...,Background offensive,Migrants,0.0,NaN,NaN,NaN,NaN,1
5,https://www.facebook.com/228735667216_10153273...,You only see what you want to see. Pretty much...,Other offensive,Commenter,1.0,1.0,1.0,0.0,0.0,1

In [41]:
# Now we prepare the dataframe as instructed by the SimpleTransformers, taking only the two relevant columns - Comment and 'binary-hate-speech'
hs_sheet = sheet2[["Comment", "binary-hate-speech"]]

# Rename the columns
hs_sheet.columns=["text", "labels"]

hs_sheet

                                                   text labels
0                Can we shut up about refugees already?      0
1     Why should we? It's the biggest humanitarian c...      0
2     these refugees adult males are cowards for not...      1
4     They are all mentally jerking off to the refug...      1
5     You only see what you want to see. Pretty much...      1
...                                                 ...    ...
5701  No multiculturalism = no inter-ethnic violence...      1
5702  Personally, I agree with those who view multic...      0
5703  And by the way these people represent abt 30% ...      1
5704  This is reality for my country today... Someti...      0
5705  Hey, lets send someone from Swedish press acro...      1

[5440 rows x 2 columns]

In [42]:
# We will use all data, annotated for implicitness (instances up to index 1096) as test data and everything else as train data:
hs_sheet.loc[:1097,"split"] = 'test'
hs_sheet.loc[1097:,"split"] = 'train'

hs_sheet.head()

                                                text labels split
0             Can we shut up about refugees already?      0  test
1  Why should we? It's the biggest humanitarian c...      0  test
2  these refugees adult males are cowards for not...      1  test
4  They are all mentally jerking off to the refug...      1  test
5  You only see what you want to see. Pretty much...      1  test

In [44]:
hs_sheet.tail()

                                                   text labels  split
5701  No multiculturalism = no inter-ethnic violence...      1  train
5702  Personally, I agree with those who view multic...      0  train
5703  And by the way these people represent abt 30% ...      1  train
5704  This is reality for my country today... Someti...      0  train
5705  Hey, lets send someone from Swedish press acro...      1  train

In [45]:
hs_sheet.split.value_counts()

train    4391
test     1049
Name: split, dtype: int64

In [46]:
# Save the created file in a csv format
hs_sheet.to_csv("data/hatespeech_binary_dataset.csv", sep="\t")